name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Generate mocks
        run: make generate

      - name: Check for changes after mock generation
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Error: Generated files are out of sync. Please run 'make generate' locally and commit the changes."
            git status --porcelain
            git diff
            exit 1
          fi

      - name: Build binary
        run: make bin

      - name: Run tests
        run: make check

      - name: Run golangci-lint
        run: make golangci

